### ISSUE TITLE
Failsafe from rollbar-gem. Mysql2::Error: "Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (116)" in /var/www/avalon/vendor/bundle/ruby/2.3.0/gems/mysql2-0.3.21/lib/mysql2/client.rb:70:in `connect': build_item in exception_d

### ISSUE THREAD

**Issue by cwant** [ualbertalib/avalon#244]
View details in Rollbar: [https://rollbar.com/ualbertalib/avalon/items/51/](https://rollbar.com/ualbertalib/avalon/items/51/)

```
Failsafe from rollbar-gem. Mysql2::Error: "Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (116)" in /var/www/avalon/vendor/bundle/ruby/2.3.0/gems/mysql2-0.3.21/lib/mysql2/client.rb:70:in `connect': build_item in exception_data
```

**Comment by cwant** [comment]
Transient issue, the system has since recovered.
