### ISSUE TITLE
Avalon v6.4.3. & v6.5: 13GB master file batch ingest fails - timed out

### ISSUE THREAD

**Issue by jefferya** [ualbertalib/avalon#650]
Avalon v6.5 during a batch ingest of a 13GB master file we receive a "Timed out reading data from server" error on the master file. If we look at the Matterhorn admin tools, we can see the master file in the processing queue and after about 22min, Matterhorn successfully completes processing the file according to the Matterhorn admin interface. However, the Fedora MasterFile object contains the a failed status code and error "Timed out reading data from server" as does the UI. Also, the logs don't show the "active_encode_update" Job as being kicked off.

Digging a bit further, it seems like the following call is not waiting long enough for Matterhorn to respond to a rest call.  Is there a way to increase the timeout on this call:

encode_job = encode.create!

https://github.com/avalonmediasystem/avalon/blob/v6.5.0/app/jobs/active_encode_job.rb#L43

Proposed solution from the Avalon community:

---

we had a similar problem with huge masterfiles (avalon v. 6.4.2, manual installation)

You can try to adjust the read-timeout. We did it this way:
- create a new file ../config/initializers/timeout.rb
- timeout.rb with the following content-->

```
require 'net/http'

# Lengthen timeout in Net::HTTP
module Net
    class HTTP
    alias old_initialize initialize

        def initialize(*args)
            old_initialize(*args)
            @read_timeout = 5*60     # 5 minutes in our setup
        end
    end
end
```

**Comment by jefferya** [comment]
More details: the active_encode_job calls the 
* [active_encode Gem](https://github.com/samvera-labs/active_encode) 
* [rubyhorn Gem](https://github.com/avalonmediasystem/rubyhorn/tree/master/lib/rubyhorn/rest_client)
* [rest-client](https://github.com/rest-client/rest-client)

>  "/home/app/gems/ruby/2.5.0/gems/rest-client-2.0.2/lib/restclient/resource.rb:67:in `post'",
 "/home/app/gems/ruby/2.5.0/bundler/gems/rubyhorn-57c12f23344d/lib/rubyhorn/rest_client/common.rb:60:in `post'",
 "/home/app/gems/ruby/2.5.0/bundler/gems/rubyhorn-57c12f23344d/lib/rubyhorn/rest_client/ingest.rb:39:in `addMediaPackageWithUrl'",
 "/home/app/gems/ruby/2.5.0/gems/active_encode-0.1.1/lib/active_encode/engine_adapters/matterhorn_adapter.rb:13:in `create'",
 "/home/app/gems/ruby/2.5.0/gems/active_encode-0.1.1/lib/active_encode/core.rb:47:in `block in create!'",
 "/home/app/gems/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:98:in `run_callbacks'",
 "/home/app/gems/ruby/2.5.0/gems/active_encode-0.1.1/lib/active_encode/core.rb:46:in `create!'",
