### ISSUE TITLE
[Spike] Avalon v6.5 update: investigate waveform backfill failures

### ISSUE THREAD

**Issue by jefferya** [ualbertalib/avalon#665]
The waveform backfill script run as part of the Avalon v6.5 upgrade creates a queued ActiveJob for each masterfile that uses FFMpeg to generate a waveform. 

At about the halfway point, the waveform generation is failing on 22 masterfiles with "Does not appear to be a valid wave file",  in <https://era-av.library.ualberta.ca/jobs/failed>. Further investigation required. 

Hypothesis: I think this is the error message I've seen when the masterfile has no audio track (i.e., not waveform possible) or the masterfile is corrupt. 

Reference: 
* the waveform backfill script: <https://github.com/ualbertalib/avalon/blob/master/script/waveform_backfill.rb>
* update process
  * https://wiki.dlib.indiana.edu/display/VarVideo/Upgrading+Avalon+6.4+to+Avalon+6.5
  * https://github.com/ualbertalib/avalon/releases/tag/v6.5.0.20200514.uofa

**Comment by jefferya** [comment]
Related to the following issue #661: find items without a waveform

Interim list of masterfiles with waveform errors -- need to lookup the associated mediaObject test with the mediaplayer: 
```
p2676w19j
fx719n23z
pk02cb45f
8s45q954r
4m90dw21h
zk51vh46t
5d86p086p
05741s465
8p58pd57b
3x816n24g
79407x77p
n296wz86d
q524jp338
5q47rp34r
tm70mw23k
f7623d15f
3t945r26s
4b29b700f
1n79h4894
td96k346k
zp38wd16m
jd472x32z
```

**Comment by jefferya** [comment]
Retried one of the failed waveforms:
```
[ActiveJob] [WaveformJob] [4891aaf8-cf08-4850-b122-f75a18676d50] Performing WaveformJob (Job ID: 4891aaf8-cf08-4850-b122-f75a18676d50) from Resque(default) with arguments: "jw827c394"
[ActiveJob] [WaveformJob] [4891aaf8-cf08-4850-b122-f75a18676d50] Attempted to init base path `production`, but it already exists
[ActiveJob] [WaveformJob] [4891aaf8-cf08-4850-b122-f75a18676d50] Error performing WaveformJob (Job ID: 4891aaf8-cf08-4850-b122-f75a18676d50) from Resque(default) in 1044.16ms: WaveFile::InvalidFormatError (Does not appear to be a valid Wave file):
/var/www/avalon6/vendor/bundle/ruby/2.6.0/gems/wavefile-1.0.1/lib/wavefile/reader.rb:46:in `rescue in initialize'
/var/www/avalon6/vendor/bundle/ruby/2.6.0/gems/wavefile-1.0.1/lib/wavefile/reader.rb:43:in `initialize'
/var/www/avalon6/app/services/waveform_service.rb:55:in `new'
/var/www/avalon6/app/services/waveform_service.rb:55:in `gather_peaks'
/var/www/avalon6/app/services/waveform_service.rb:39:in `get_normalized_peaks'
/var/www/avalon6/app/services/waveform_service.rb:31:in `get_waveform_json'
/var/www/avalon6/app/jobs/waveform_job.rb:26:in `perform'
/var/www/avalon6/vendor/bundle/ruby/2.6.0/gems/activejob-5.2.4.4/lib/active_job/execution.rb:39:in `block in perform_now'
/var/www/avalon6/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
/var/www/avalon6/vendor/bundle/ruby/2.6.0/gems/activejob-traffic_control-0.1.3/lib/active_job/traffic_control/disable.rb:44:in `block (2 levels) in <module:Disable>'
/var/www/avalon6/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:118:in `instance_exec'
/var/www/avalon6/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/var/www/avalon6/vendor/bundle/ruby/2.6.0/gems/activejob-traffic_control-0.1.3/lib/active_job/traffic_control/throttle.rb:50:in `block (2 levels) in <module:Throttle>'
/var/www/avalon6/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:118:in `instance_exec'
/var/www/avalon6/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/var/www/avalon6/vendor/bundle/ruby/2.6.0/gems/activejob-traffic_control-0.1.3/lib/active_job/traffic_control/concurrency.rb:56:in `block (2 levels) in <module:Concurrency>'
/var/www/avalon6/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:118:in `instance_exec'
/var/www/avalon6/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/var/www/avalon6/vendor/bundle/ruby/2.6.0/gems/i18n-1.8.9/lib/i18n.rb:314:in `with_locale'
/var/www/avalon6/vendor/bundle/ruby/2.6.0/gems/activejob-5.2.4.4/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
/var/www/avalon6/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:118:in `instance_exec'
/var/www/avalon6/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/var/www/avalon6/vendor/bundle/ruby/2.6.0/gems/activejob-5.2.4.4/lib/active_job/logging.rb:26:in `block (4 levels) in <module:Logging>'
/var/www/avalon6/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/notifications.rb:168:in `block in instrument'
/var/www/avalon6/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/var/www/avalon6/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/notifications.rb:168:in `instrument'
/var/www/avalon6/vendor/bundle/ruby/2.6.0/gems/activejob-5.2.4.4/lib/active_job/logging.rb:25:in `block (3 levels) in <module:Logging>'
/var/www/avalon6/vendor/bundle/ruby/2.6.0/gems/activejob-5.2.4.4/lib/active_job/logging.rb:46:in `block in tag_logger'
/var/www/avalon6/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/tagged_logging.rb:71:in `block in tagged'
/var/www/avalon6/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/tagged_logging.rb:28:in `tagged'
/var/www/avalon6/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/tagged_logging.rb:71:in `tagged'
/var/www/avalon6/vendor/bundle/ruby/2.6.0/gems/activejob-5.2.4.4/lib/active_job/logging.rb:46:in `tag_logger'
/var/www/avalon6/vendor/bundle/ruby/2.6.0/gems/activejob-5.2.4.4/lib/active_job/logging.rb:22:in `block (2 levels) in <module:Logging>'
/var/www/avalon6/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:118:in `instance_exec'
/var/www/avalon6/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/var/www/avalon6/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:136:in `run_callbacks'
/var/www/avalon6/vendor/bundle/ruby/2.6.0/gems/activejob-5.2.4.4/lib/active_job/execution.rb:38:in `perform_now'
/var/www/avalon6/vendor/bundle/ruby/2.6.0/gems/activejob-5.2.4.4/lib/active_job/execution.rb:24:in `block in execute'
/var/www/avalon6/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
/var/www/avalon6/vendor/bundle/ruby/2.6.0/gems/activejob-5.2.4.4/lib/active_job/railtie.rb:28:in `block (4 levels) in <class:Railtie>'
/var/www/avalon6/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/execution_wrapper.rb:87:in `wrap'
/var/www/avalon6/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/reloader.rb:73:in `block in wrap'
/var/www/avalon6/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/execution_wrapper.rb:87:in `wrap'
/var/www/avalon6/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/reloader.rb:72:in `wrap'
/var/www/avalon6/vendor/bundle/ruby/2.6.0/gems/activejob-5.2.4.4/lib/active_job/railtie.rb:27:in `block (3 levels) in <class:Railtie>'
/var/www/avalon6/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:118:in `instance_exec'
/var/www/avalon6/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/var/www/avalon6/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:136:in `run_callbacks'
/var/www/avalon6/vendor/bundle/ruby/2.6.0/gems/activejob-5.2.4.4/lib/active_job/execution.rb:22:in `execute'
/var/www/avalon6/vendor/bundle/ruby/2.6.0/gems/activejob-5.2.4.4/lib/active_job/queue_adapters/resque_adapter.rb:47:in `perform'
/var/www/avalon6/vendor/bundle/ruby/2.6.0/gems/resque-2.0.0/lib/resque/job.rb:168:in `perform'
/var/www/avalon6/vendor/bundle/ruby/2.6.0/gems/resque-2.0.0/lib/resque/worker.rb:308:in `perform'
/var/www/avalon6/vendor/bundle/ruby/2.6.0/gems/resque-2.0.0/lib/resque/worker.rb:897:in `block in perform_with_fork'
/var/www/avalon6/vendor/bundle/ruby/2.6.0/gems/resque-2.0.0/lib/resque/worker.rb:895:in `fork'
/var/www/avalon6/vendor/bundle/ruby/2.6.0/gems/resque-2.0.0/lib/resque/worker.rb:895:in `perform_with_fork'
/var/www/avalon6/vendor/bundle/ruby/2.6.0/gems/resque-2.0.0/lib/resque/worker.rb:264:in `work_one_job'
/var/www/avalon6/vendor/bundle/ruby/2.6.0/gems/resque-2.0.0/lib/resque/worker.rb:238:in `block in work'
/var/www/avalon6/vendor/bundle/ruby/2.6.0/gems/resque-2.0.0/lib/resque/worker.rb:235:in `loop'
/var/www/avalon6/vendor/bundle/ruby/2.6.0/gems/resque-2.0.0/lib/resque/worker.rb:235:in `work'
/var/www/avalon6/vendor/bundle/ruby/2.6.0/gems/resque-2.0.0/lib/resque/tasks.rb:20:in `block (2 levels) in <main>'
/var/www/avalon6/vendor/bundle/ruby/2.6.0/gems/rake-13.0.3/lib/rake/task.rb:281:in `block in execute'
/var/www/avalon6/vendor/bundle/ruby/2.6.0/gems/rake-13.0.3/lib/rake/task.rb:281:in `each'
/var/www/avalon6/vendor/bundle/ruby/2.6.0/gems/rake-13.0.3/lib/rake/task.rb:281:in `execute'
/var/www/avalon6/vendor/bundle/ruby/2.6.0/gems/rake-13.0.3/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/usr/lib64/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/var/www/avalon6/vendor/bundle/ruby/2.6.0/gems/rake-13.0.3/lib/rake/task.rb:199:in `invoke_with_call_chain'
/var/www/avalon6/vendor/bundle/ruby/2.6.0/gems/rake-13.0.3/lib/rake/task.rb:188:in `invoke'
/var/www/avalon6/vendor/bundle/ruby/2.6.0/gems/rake-13.0.3/lib/rake/application.rb:160:in `invoke_task'
/var/www/avalon6/vendor/bundle/ruby/2.6.0/gems/rake-13.0.3/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/var/www/avalon6/vendor/bundle/ruby/2.6.0/gems/rake-13.0.3/lib/rake/application.rb:116:in `each'
/var/www/avalon6/vendor/bundle/ruby/2.6.0/gems/rake-13.0.3/lib/rake/application.rb:116:in `block in top_level'
/var/www/avalon6/vendor/bundle/ruby/2.6.0/gems/rake-13.0.3/lib/rake/application.rb:125:in `run_with_threads'
/var/www/avalon6/vendor/bundle/ruby/2.6.0/gems/rake-13.0.3/lib/rake/application.rb:110:in `top_level'
/var/www/avalon6/vendor/bundle/ruby/2.6.0/gems/rake-13.0.3/lib/rake/application.rb:83:in `block in run'
/var/www/avalon6/vendor/bundle/ruby/2.6.0/gems/rake-13.0.3/lib/rake/application.rb:186:in `standard_exception_handling'
/var/www/avalon6/vendor/bundle/ruby/2.6.0/gems/rake-13.0.3/lib/rake/application.rb:80:in `run'
/var/www/avalon6/vendor/bundle/ruby/2.6.0/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
/var/www/avalon6/vendor/bundle/ruby/2.6.0/bin/rake:23:in `load'
/var/www/avalon6/vendor/bundle/ruby/2.6.0/bin/rake:23:in `<top (required)>'
/usr/lib64/ruby/site_ruby/2.6.0/bundler/cli/exec.rb:63:in `load'
/usr/lib64/ruby/site_ruby/2.6.0/bundler/cli/exec.rb:63:in `kernel_load'
/usr/lib64/ruby/site_ruby/2.6.0/bundler/cli/exec.rb:28:in `run'
/usr/lib64/ruby/site_ruby/2.6.0/bundler/cli.rb:494:in `exec'
/usr/lib64/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/lib64/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/lib64/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/usr/lib64/ruby/site_ruby/2.6.0/bundler/cli.rb:30:in `dispatch'
/usr/lib64/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/usr/lib64/ruby/site_ruby/2.6.0/bundler/cli.rb:24:in `start'
/usr/lib64/ruby/gems/2.6.0/gems/bundler-2.2.14/exe/bundle:49:in `block in <top (required)>'
/usr/lib64/ruby/site_ruby/2.6.0/bundler/friendly_errors.rb:130:in `with_friendly_errors'
/usr/lib64/ruby/gems/2.6.0/gems/bundler-2.2.14/exe/bundle:37:in `<top (required)>'
/usr/bin/bundle:23:in `load'
/usr/bin/bundle:23:in `<main>'
```

**Comment by jefferya** [comment]
Investigation to the scale of the waveform failures: 284 items (based on masterfiles with Solr property`has_waveform?_bs` != true)

Discovered causes:

* media file name or collection name contains an apostrophe then the waveform creation fails 

* media file doesn't have an audio track therefore no waveform created thus error (note: fixed in upstream https://github.com/avalonmediasystem/avalon/pull/4261 plus perhaps other commits as well)

**Comment by jefferya** [comment]
```require 'json'
require 'net/http'
require 'uri'

uri_str="#{ENV['SOLR_URL']}select?fq=has_model_ssim:MasterFile&fl=id,isPartOf_ssim,has_waveform?_bs,file_location_ssi&rows=1000000&wt=json&sort=file_location_ssi asc, id asc"

uri = URI.parse(uri_str)
response = Net::HTTP.get_response(uri)

result = JSON.parse(response.body)
result["response"]["docs"].each do |doc|
  puts "#{doc['id']},#{doc['isPartOf_ssim']},#{doc['has_waveform?_bs']},#{doc['file_location_ssi']}" unless doc['has_waveform?_bs'] == true
end

```
