### ISSUE TITLE
`edit structure` operation fails for MediaObject `mk61rj10w `

### ISSUE THREAD

**Issue by jefferya** [ualbertalib/avalon#748]
HTTP 500 error <https://era-av.library.ualberta.ca/media_objects/mk61rj10w/edit?step=structure>

```
method=GET path=/media_objects/mk61rj10w/edit format=html controller=MediaObjectsController action=edit status=500 error='ActionView::Template::Error: incompatible character encodings: UTF-8 and ASCII-8BIT' duration=4506.83 view=0.00 db=3.28 time=2494125.58

ActionView::Template::Error (incompatible character encodings: UTF-8 and ASCII-8BIT):
    94:             <% end %>
    95:           </div>
    96:           <% if section.captions.present? %>
    97:             <div class="structure_view">Uploaded file: <%= section.captions.original_name %></div>
    98:           <% end %>
    99:         </div>
   100:       </li>

app/views/media_objects/_structure.html.erb:97:in `block in _app_views_media_objects__structure_html_erb__763344923819196357_70342538211520'
app/views/media_objects/_structure.html.erb:27:in `each'
app/views/media_objects/_structure.html.erb:27:in `each_with_index'
app/views/media_objects/_structure.html.erb:27:in `_app_views_media_objects__structure_html_erb__763344923819196357_70342538211520'
app/views/media_objects/edit.html.erb:28:in `_app_views_media_objects_edit_html_erb__2877677242272686410_70342657493840'

```

Also, a second test: https://era-av.library.ualberta.ca/media_objects/mk61rj10w.json

```
method=GET path=/media_objects/mk61rj10w.json format=json controller=MediaObjectsController action=show status=500 error='Encoding::UndefinedConversionError: "\xEF" from ASCII-8BIT to UTF-8' duration=23897.41 view=0.00 db=14.62 time=2494148.80

Encoding::UndefinedConversionError ("\xEF" from ASCII-8BIT to UTF-8):

app/controllers/media_objects_controller.rb:339:in `block (2 levels) in show'
app/controllers/media_objects_controller.rb:328:in `show'
app/controllers/application_controller.rb:78:in `handle_api_request'
```

**Comment by jefferya** [comment]
Error appears to be in `captions` attached to Masterfiles.

Steps to reproduce
```
z = MediaObject.find('mk61rj10w');
y = z.as_json;
y.to_json
y[:files][0][:captions].to_json
```

**Comment by jefferya** [comment]
Fixed the filename problem with the aforementioned approach.

The JSON representation of the media object fails if the caption file contains a byte-order mark or non UTF-8 characters. E.G., path=/media_objects/mk61rj10w.json

**Comment by jefferya** [comment]
Fixed the filename problem with the aforementioned approach.

The JSON representation of the media object fails if the caption file contains a byte-order mark or non UTF-8 characters. E.G., path=/media_objects/mk61rj10w.json. Unused except by transition; will address in #753
